In [1]:
import numpy as np

In [ ]:
s = 0,m = 1,l = 2
-1 = 0 ,1 = 1

In [7]:
    datasets = np.array([[1,1,1,1,1,2,2,2,2,2,3,3,3,3,3],
                  [0,1,1,0,0,0,1,1,2,2,2,1,1,2,2],
                  [0,0,1,1,0,0,0,1,1,1,1,1,1,1,0]]).T

In [8]:
datasets.shape


(15, 3)

In [9]:
Y_1 = np.sum(datasets[:,-1]) / datasets.shape[0]
print(Y_1)

0.6


In [11]:
Y_0 = 1-Y_1
Y_0


0.4

In [12]:
index_1 = np.where(datasets[:,-1]==1)
index_1

(array([ 2,  3,  7,  8,  9, 10, 11, 12, 13], dtype=int64),)

In [14]:
y_1_dataset = datasets[index_1]
y_1_dataset

array([[1, 1, 1],
       [1, 0, 1],
       [2, 1, 1],
       [2, 2, 1],
       [2, 2, 1],
       [3, 2, 1],
       [3, 1, 1],
       [3, 1, 1],
       [3, 2, 1]])

In [21]:
X1_2 = np.where(y_1_dataset[:,0]==2)[0].shape[0] / y_1_dataset.shape[0]
X1_2

0.3333333333333333

In [22]:
X2_0 = np.where(y_1_dataset[:,1]==0)[0].shape[0] / y_1_dataset.shape[0]
X2_0

0.1111111111111111

In [24]:
p_1 = X1_2* X2_0*Y_1
p_1

0.02222222222222222

In [25]:
index_0 = np.where(datasets[:,-1]==0)
index_0

(array([ 0,  1,  4,  5,  6, 14], dtype=int64),)

In [26]:
y_0_dataset = datasets[index_0]
y_0_dataset

array([[1, 0, 0],
       [1, 1, 0],
       [1, 0, 0],
       [2, 0, 0],
       [2, 1, 0],
       [3, 2, 0]])

In [27]:
X1_2 = np.where(y_1_dataset[:,0]==2)[0].shape[0] / y_1_dataset.shape[0]
X1_2

0.3333333333333333

In [29]:
X2_0 = np.where(y_0_dataset[:,1]==0)[0].shape[0] / y_0_dataset.shape[0]
X2_0

0.5

In [30]:
X1_2 * X2_0 * Y_0

0.06666666666666667