In [47]:
import numpy as np
path = "/Users/a/Desktop/Classic_machine_learning-master/data_set/datingTestSet.txt"

In [49]:
data=[]
labels = []
open_file = open(file=path,mode='r',encoding='gbk')
str = open_file.read()
# print(str)
lines  =str.split('\n')
# print(lines)
for line in lines:
    haha  = line.split('\t')
    x1,x2,x3,label = float(haha[0]),float(haha[1]),float(haha[2]),haha[3]
    for i in label:
        if label=='largeDoses':
            label=0
        elif label=='smallDoses':
            label=1
        else:
            label=2
#     print([x1,x2,x3,lable])
    data.append([x1,x2,x3])
    labels.append(label)
data = np.array(data)
labels = np.array(label)
print(data)
print(labels)

[[4.0920000e+04 8.3269760e+00 9.5395200e-01]
 [1.4488000e+04 7.1534690e+00 1.6739040e+00]
 [2.6052000e+04 1.4418710e+00 8.0512400e-01]
 ...
 [2.6575000e+04 1.0650102e+01 8.6662700e-01]
 [4.8111000e+04 9.1345280e+00 7.2804500e-01]
 [4.3757000e+04 7.8826010e+00 1.3324460e+00]]
2


In [50]:
len(data)

1000

In [51]:
data

array([[4.0920000e+04, 8.3269760e+00, 9.5395200e-01],
       [1.4488000e+04, 7.1534690e+00, 1.6739040e+00],
       [2.6052000e+04, 1.4418710e+00, 8.0512400e-01],
       ...,
       [2.6575000e+04, 1.0650102e+01, 8.6662700e-01],
       [4.8111000e+04, 9.1345280e+00, 7.2804500e-01],
       [4.3757000e+04, 7.8826010e+00, 1.3324460e+00]])

In [52]:
max  = np.max(data,axis=0)
min = np.min(data,axis=0)
print(max)
print(min)

[9.1273000e+04 2.0919349e+01 1.6955170e+00]
[0.       0.       0.001156]


In [53]:
new_data = (data-min)/(max-min)

In [54]:
new_data

array([[0.44832535, 0.39805139, 0.56233353],
       [0.15873259, 0.34195467, 0.98724416],
       [0.28542943, 0.06892523, 0.47449629],
       ...,
       [0.29115949, 0.50910294, 0.51079493],
       [0.52711097, 0.43665451, 0.4290048 ],
       [0.47940793, 0.3768091 , 0.78571804]])

In [60]:
from sklearn.model_selection import train_test_split

In [62]:
(x_train,x_test),(y_train,y_test) = train_test_split(new_data,labels,test_size=0.33,random_state=42)

TypeError: Singleton array array(2) cannot be considered a valid collection.

In [59]:

x_train.shape


NameError: name 'x_train' is not defined

In [ ]:
def KNN_model(train_data,test_data,K):
    #
